services:
  proxy:
    container_name: local-proxy
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
