services:
    laravel.test:
        build:
            context: ../../../example/vendor/laravel/sail/runtimes/8.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: 1000
        image: sail-8.4/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        expose:
            - '80'
        environment:
            VIRTUAL_HOST: example.local
            WWWUSER: 1000
            LARAVEL_SAIL: 1
            XDEBUG_MODE: 'debug,coverage' #develop
            XDEBUG_CONFIG: 'client_host=host.docker.internal'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '../../../example:/var/www/html'
            - '../../provision/container/sail-php.sh:/usr/bin/sail-php'
            - '../../provision/container/sail-php.ini:/etc/php/8.4/cli/conf.d/99-sail.ini'
            # Enable if composer auth should be mounted:
            #- '~/.config/composer/auth.json:/home/sail/.config/composer/auth.json'
        networks:
            - sail
            - proxy
        depends_on:
            - mysql
            - redis
        restart: unless-stopped
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '33006:3306'
        expose:
            - '3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - '../../provision/container/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
        restart: unless-stopped
    redis:
        image: 'redis:alpine'
        expose:
            - '6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
        restart: unless-stopped

networks:
    sail:
        driver: bridge
    proxy:
        external: true

volumes:
    sail-mysql:
        driver: local
        # This speeds up test execution by a huge amount, but data will be lost after shutdown
        driver_opts:
            type: tmpfs
            device: tmpfs
    sail-redis:
        driver: local
        driver_opts:
            type: tmpfs
            device: tmpfs
