services:
    laravel.test:
        build:
            context: ${LARAVEL_RUNTIME_DIRECTORY}/runtime/sail
            dockerfile: Dockerfile
            args:
                PHP_VERSION: '${PHP_VERSION:-8.4}'
        image: php-runtime-${PHP_VERSION:-8.4}/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        expose:
            - '80'
        environment:
            VIRTUAL_HOST: ${PROJECT_NAME}.local
            WWWUSER: 1000
            LARAVEL_SAIL: 1
            XDEBUG_MODE: 'debug,coverage'
            XDEBUG_CONFIG: 'client_host=host.docker.internal'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '${PROJECT_PATH}:/var/www/html'
        networks:
            - sail
            - proxy
        restart: unless-stopped

networks:
    sail:
        driver: bridge
    proxy:
        external: true
